// Generated by Selenium IDE
package commontests;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import org.testng.annotations.Test;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
public class TarifAdmissionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  /*public void setUp() {
     System.setProperty("webdriver.chrome.driver","C:\\Users\\R.Pereira\\Documents\\NetBeansProjects\\SeleniumTest01\\SeleniumTest01\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }*/
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tarifAdmission(Connection Connection) throws FileNotFoundException {
      /*chrome et firefox*/
    System.setProperty("webdriver.chrome.driver","C:\\Users\\R.Pereira\\Documents\\NetBeansProjects\\SeleniumTest01\\SeleniumTest01\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    WebDriverWait wait = new WebDriverWait (driver, 15);     
    Actions action = new Actions(driver);
    
    String filename="C:\\Users\\R.Pereira\\Documents\\NetBeansProjects\\mavenproject\\docs\\data2.csv";
    //String filename = "..\\..\\..\\..\\docs\\data2.csv";
    //String filename = "docs\\data2.csv";
    File file = new File(filename);
    
    double finalTarifValue = 0;
    int i =0;
        
    try{
        Scanner inputStream = new Scanner(file);
        while(inputStream.hasNext()){
            String dataCSV = inputStream.next();
            String[] values = dataCSV.split(";");

         int idEnfant = Integer.parseInt(values[0]);
         int idActivity = Integer.parseInt(values[2]);
         String prixHoraireString = values[6].replaceAll("^\"|\"$", "");
         double prixHoraire = Double.parseDouble(prixHoraireString.replace(",","."));
         
         Statement stmt = Connection.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT v.designation FROM t_activite a JOIN t_vrs v ON v.id_vrs = a.id_vrs WHERE a.id_activite ="+idActivity);
         
         String structureName = null;
         while (rs.next()) {
            structureName =  rs.getString(1);
        }
        
        // get url to start
        driver.get("https://batgirl.agoraplus.fr/agora/pck_security.home");
        driver.manage().window().setSize(new Dimension(1522, 807));
        
        // closing coockies
        driver.findElement(By.id("cookieChoiceDismiss")).click();
        
        //Login into Backoffice
        driver.findElement(By.cssSelector(".dock-item:nth-child(1) > img")).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id='login']/form/div/div/div[2]/input"))).sendKeys("admin");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id='login']/form/div/div/div[3]/input"))).sendKeys("bl@nQui13");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'logIn\']/img"))).click();
        
        //go to research page and search the kid we send it
        while(driver.findElement(By.xpath("//*[@id=\'menuLeft\']/div[2]/p[1]/a")).isDisplayed() != true){
            
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[1]/div[1]/div/ul/li[2]/a"))).click();
            i++;
            driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
            if(i > 100){
                break;
            }
        }
        
        i=0;
        while(driver.findElement(By.xpath("//*[@id=\'menuLeft\']/div[2]/ul[1]/li[1]/a")).isDisplayed() != true){
            
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'menuLeft\']/div[2]/p[1]/a"))).click();
            i++;
            if(i > 100){
                break;
            }
        }
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'menuLeft\']/div[2]/ul[1]/li[1]/a"))).click();
        
        String currentUrl = driver.getCurrentUrl();
        String newUrl = currentUrl;
        
        i=0;
        //Make the search for the kid sended
        while (newUrl.equals(currentUrl)){
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[2]/div[4]/div[2]/form/div/input"))).click();
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[2]/div[4]/div[2]/form/div/input"))).sendKeys(""+idEnfant+"");
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[2]/div[4]/div[2]/form/div/img"))).click();
            newUrl = driver.getCurrentUrl();
            i++;
            if(i > 100){
                break;
            }
        }
        
        i=0;
        //open tab admission
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        while(true){
            
            action.moveToElement(driver.findElement(By.xpath("//*[@id=\'tabs\']/ul/li[2]/a")));
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'tabs\']/ul/li[2]/a"))).click();
            driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
            
            driver.findElement(By.xpath("/html/body/div[2]/div[2]/div[2]/ul/li[2]")).getClass();
            
            String classes = driver.findElement(By.xpath("/html/body/div[2]/div[2]/div[2]/ul/li[2]")).getAttribute("class");
            if (classes.equals("ui-state-default ui-corner-top ui-state-hover ui-tabs-selected ui-state-active")){
                break;
            }
            i++;
            if(i > 100){
                break;
            }
        }
        
        //Select Structure in the dropdown and get tarif horaire
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[2]/div[2]/div[2]/form/table/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/button"))).click();
        String activityName = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'etab-UL\']/li[6]/label/span"))).getText();
        if(activityName.equals(""+structureName+"")){
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\'etab-UL\']/li[6]/label/span"))).click();
            String tarif = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[2]/div[2]/div[2]/div[2]/form/table/tbody/tr[1]/td/table/tbody/tr[8]/td[2]/span"))).getText();
            String[] part = tarif.split(" ");
            String tarifValue = part[0];
            finalTarifValue = Double.parseDouble(tarifValue); 
            //System.out.println(finalTarifValue);
        }
         
        if (finalTarifValue == prixHoraire){
            System.out.println("Passed");
        } else {
            System.out.println("Failue - on the kid:"+idEnfant+" for the activity:"+idActivity+". Value Obtained:"+finalTarifValue+" Value Expected:"+prixHoraire);
        }
      }
        System.out.println("fim");
    }catch(Exception e){
        System.out.println("Test Failed");
        driver.quit();
        e.printStackTrace();
    }finally{
        driver.quit();
    }
  }
}
